#!/bin/sh

SRC_DIR="/sinix/declare/src/"
DOTFILES_DIR="~/yourcustomfolderksfldajsdfw"

if [ "$EUID" -ne 0 ]; then
        echo "ABORT: Run this as root or with sudo/doas."
fi

echo ":: Applying changes..."
lua $SRC_DIR/main.lua

echo ":: Overwriting existing dotfiles symlink..."
echo "[!!] EDIT THIS FILE (/usr/local/bin/sinix-rebuild) TO MAKE IT USE YOUR CUSTOM FOLDER."
echo "if already feelin' comfortable, delete the 'sleep 10' from this script, and this text here."
sleep 10
ln -sf $DOTFILES_DIR ~/.config
echo ":)"
